[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/var/run/supervisord.pid

[program:tor]
command=/usr/bin/tor -f /etc/tor/torrc
user=tor
autostart=true
autorestart=true
stderr_logfile=/var/log/tor.log
stdout_logfile=/var/log/tor.out

[program:Xvfb]
command=/usr/bin/Xvfb :99 -screen 0 1024x768x16
autostart=true
autorestart=true
stderr_logfile=/var/log/xvfb.log
stdout_logfile=/var/log/xvfb.out

[program:openbox]
command=/usr/bin/openbox
environment=DISPLAY=:99
autostart=true
autorestart=true
stderr_logfile=/var/log/openbox.log
stdout_logfile=/var/log/openbox.out

[program:x11vnc]
command=/usr/bin/x11vnc -display :99 -forever -shared -rfbport 5900 -noxdamage -repeat -nb -noxrecord -noxfixes -noxshm -noshm -noxcursor
environment=DISPLAY=:99
autostart=true
autorestart=true
stderr_logfile=/var/log/x11vnc.log
stdout_logfile=/var/log/x11vnc.out

[program:novnc]
command=/opt/noVNC/utils/novnc_proxy --listen 6080 --vnc localhost:5900
autostart=true
autorestart=true
stderr_logfile=/var/log/novnc.log
stdout_logfile=/var/log/novnc.out

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stderr_logfile=/var/log/nginx.error.log
stdout_logfile=/var/log/nginx.access.log
